### ISSUE TITLE
Some tasks error out

### ISSUE THREAD

**Issue by treba123** [liqd/a4-meinberlin#2190]
Notification email for mein.berlin.de:

```
Error in Task [[430], {}], see: /django-admin/background_task/completedtask/39589/change/ 
Error in Task [[431], {}], see: /django-admin/background_task/completedtask/39327/change/ 
Error in Task [[431], {}], see: /django-admin/background_task/completedtask/38819/change/ 
Error in Task [[431], {}], see: /django-admin/background_task/completedtask/38755/change/ 
Error in Task [[431], {}], see: /django-admin/background_task/completedtask/37583/change/ 
Error in Task [[431], {}], see: /django-admin/background_task/completedtask/37579/change/ 
Error in Task [[430], {}], see: /django-admin/background_task/completedtask/37374/change/ 
Error in Task [[430], {}], see: /django-admin/background_task/completedtask/37373/change/ 
Error in Task [["meinberlin.apps.notifications.emails", "NotifyFollowersOnNewItemCreated", "a4actions", "action", 1164, [], {}], {}], see: /django-admin/background_task/completedtask/178/change/ 
Error in Task [["meinberlin.apps.notifications.emails", "NotifyModeratorsEmail", "a4actions", "action", 1164, [], {}], {}], see: /django-admin/background_task/completedtask/177/change/ 
Error in Task [["meinberlin.apps.notifications.emails", "NotifyCreatorEmail", "a4actions", "action", 1164, [], {}], {}], see: /django-admin/background_task/completedtask/176/change/ 
```
Task backtrace:
```
Traceback (most recent call last):
  File "/home/django/django/lib/python3.6/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/django/django/meinberlin/apps/bplan/tasks.py", line 64, in get_location_information
    point, district_pk = get_bplan_point_and_district_pk(bplan.identifier)
TypeError: 'NoneType' object is not iterable
```

and another one on stage:
```
Error in Task [["meinberlin.apps.projects.emails", "InviteParticipantEmail", "meinberlin_projects", "participantinvite", 56, [], {}], {}], see: /django-admin/background_task/completedtask/1942/change/ 
```
backtrace:
```
Traceback (most recent call last):
  File "/home/django/django/lib/python3.6/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/django/django/lib/python3.6/site-packages/adhocracy4/emails/tasks.py", line 14, in send_async
    return cls().dispatch(object, *args, **kwargs)
  File "/home/django/django/lib/python3.6/site-packages/adhocracy4/emails/base.py", line 138, in dispatch
    mail.send()
  File "/home/django/django/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/django/django/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 111, in send_messages
    sent = self._send(message)
  File "/home/django/django/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 127, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'-m.noffke@liqd.net': (501, b'5.1.3 Bad recipient address syntax')}

```

**Comment by treba123** [comment]
Hm all of them date back quite a while. I removed them for now, lets see if they pop up again
