### ISSUE TITLE
backrground task fails when Action is deleted before it is run

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4365]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** When something creates an Action, which results in notification emails being sent, and the Action is deleted before it is sent, we get an server error. The action will be deleted with the idea or comment that created the action.
**important screensize:**
**device & browser:** 
**Comment/Question:** Maybe we can do it in a4 for the projects, where we check that the organisation exists before we send the project deleted notification.
```
Traceback (most recent call last):
  File "/home/django/django/lib/python3.8/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/django/django/lib/python3.8/site-packages/adhocracy4/emails/tasks.py", line 14, in send_async
    object = model.objects.get(pk=object_pk)
  File "/home/django/django/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/django/django/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
adhocracy4.actions.models.Action.DoesNotExist: Action matching query does not exist.
```

**Comment by hklarner** [comment]
I would like to see how often this racing condition happens once celery is running. Celery workers should respond immediately whereas the background task used a sleep interval. I just checked: it seems the sleep interval was 5s, so it is surprising that such errors even occurred.

We will see those crashes on sentry. Of course we can always silently ignore such errors (e.g. by testing existence). An alternative would be to extract the data from the action and passing it to `send_async` as data. It all depends on what we would like to happen if an object (i.e. Action) is deleted before it it is queried by the email task.

I will report back once we see such errors on sentry and have actual use cases to discuss.
